services:
  frontend:
    build:
      context: Frontend
      dockerfile: Dockerfile
    restart: always
    networks:
      - app-network
  api:
    build:
      context: API
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - app-network

  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    restart: unless-stopped
    volumes:
      - ./mariaDB/data:/var/lib/mysql:rw
    networks:
      - app-network

networks:
  app-network:
    driver: bridge