services:
  frontend:
    build:
      context: Frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL=http://${API_HOST}:${API_PORT}
    restart: always
    networks:
      - app-network
  api:
    build:
      context: API
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./API/app:/usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    restart: unless-stopped
    volumes:
      - ./mariaDB/data:/var/lib/mysql:rw
    networks:
      - app-network

networks:
   app-network:
     driver: bridge