services:
  frontend:
    build:
      context: Frontend
      dockerfile: Dockerfile
    restart: always
    networks:
      - app-network
  api: 
    build:
      context: API
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - app-network
    
networks:
   app-network:
     driver: bridge