services:
  init-db:
    build:
      context: data
      dockerfile: Dockerfile
    environment:
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_EXPOSE_PORT: ${DB_EXPOSE_PORT}
      DB_HOST: ${DB_HOST}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data/hyg_v42.csv:/tmp/hyg_v42.csv
      - ./data/worldcities.csv:/tmp/worldcities.csv
      - ./data/populate_database_with_csv.py:/tmp/populate_database_with_csv.py
    command: python3 /tmp/populate_database_with_csv.py
    networks:
      - app-network
